name: pr-size

on:
  pull_request:

jobs:
  pr-size:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: cbrgm/pr-size-labeler-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Pass the GitHub token for authentication
          github_repository: ${{ github.repository }} # Pass the repository name
          github_pr_number: ${{ github.event.number }} # Pass the pull request number
          config_file_path: '.github/pr-size.yml' # Specify the path to the configuration file